### PR TITLE
Fixes for use with kernel 5.8.x

### PR DESCRIPTION
**Pull request by omegacoleman**
I wasn't aware of https://github.com/abperiasamy/rtl8812AU_8821AU_linux/pull/337 when i started, but this fix for sha256_state might be more simple.
Also needs https://github.com/abperiasamy/rtl8812AU_8821AU_linux/pull/333 https://github.com/abperiasamy/rtl8812AU_8821AU_linux/pull/316 5.3 5.6 patches for working with 5.8.x kernel

### CODE REVIEW

**Comment by omegacoleman** [comment]
the origin version got bugs after hours of using it with my device. after I encountered https://lore.kernel.org/linux-wireless/20200424212454.230080-1-geomatsi@gmail.com/ I realised that though the function looks useless to me (it only prints some logs) it somehow could not be removed (as a 'registration function'). I fixed it and it now works perfectly.

**Comment by paralin** [comment]
Hi all,

Currently Buildroot is based on 4235b0ec7d7220a6364586d8e25b1e8cb99c36f1 with this patch and #316  applied.

My version of this series of patches on top of 4235b as a base is here: https://github.com/paralin/rtl8812AU_8821AU_linux/tree/buildroot

Hope this helps.

**Comment by paralin** [comment]
making some progress there, but still running into another problem:

```
../rtl8821au-4235b0ec7d7220a6364586d8e25b1e8cb99c36f1/os_dep/linux/rtw_proc.c: In function ‘rtw_proc_create_entry’:
../rtl8821au-4235b0ec7d7220a6364586d8e25b1e8cb99c36f1/os_dep/linux/rtw_proc.c:73:67: error: passing argument 4 of ‘proc_create_data’ from incompatible pointer type [-Werror=incompatible-pointer-types]
   73 |  entry = proc_create_data(name,  S_IFREG|S_IRUGO|S_IWUGO, parent, fops, data);
      |                                                                   ^~~~
      |                                                                   |
      |                                                                   const struct file_operations *
In file included from ../rtl8821au-4235b0ec7d7220a6364586d8e25b1e8cb99c36f1/include/../os_dep/linux/rtw_proc.h:23,
                 from ../rtl8821au-4235b0ec7d7220a6364586d8e25b1e8cb99c36f1/include/osdep_intf.h:123,
                 from ../rtl8821au-4235b0ec7d7220a6364586d8e25b1e8cb99c36f1/include/drv_types.h:107,
                 from ../rtl8821au-4235b0ec7d7220a6364586d8e25b1e8cb99c36f1/os_dep/linux/rtw_proc.c:21:
./include/linux/proc_fs.h:102:31: note: expected ‘const struct proc_ops *’ but argument is of type ‘const struct file_operations *’
  102 | extern struct proc_dir_entry *proc_create_data(const char *, umode_t,

```

**Comment by omegacoleman** [comment]
hi @paralin , that's great to hear. I made a typo in the original description actually, and fails to indicate that #333 is needed too. This error is due to `fops` being splited from `procfs` and is fixed there.

**Comment by paralin** [comment]
@omegacoleman yup my branch + series submitted to buildroot mainline has that in there too

**Comment by Ecos-hj** [comment]
Your version works for me, too. 
So we shall prefer it, (EDIT: we still need a fix for Kernel 5.10)

**Comment by omegacoleman** [comment]
@Ecos-hj Thanks for letting me know.

The 5.10+ builds break because of the famous removal of `set_fs()` on `x86_64`. I issued a PR for that https://github.com/abperiasamy/rtl8812AU_8821AU_linux/pull/345, and this branch I tested works for 5.10+ https://github.com/omegacoleman/rtl8812AU_8821AU_linux/tree/kernel-5.10
